use bus_station;
drop table bus_station.drivers;
drop table bus_station.flights;
drop table bus_station.passenger_passport;
drop table bus_station.passengers;
drop table bus_station.ticket;
drop table bus_station.type_bus;
drop table bus_station.type_flight;
drop table bus_station.user_role;
drop table bus_station.usr;
drop table bus_station.hibernate_sequence;